# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dc448762fd7e802a4b49bd38d0c57a0700196d90328c74e42c4465359cd92770505883b8951af93cb731a567f8cdb9babf3974f4d2229b98ea50184e8673a27

test:
  secret_key_base: 892e2d7719e23394da50796b1235b31995771fb99ef4888ec7d901041e55d58b98ec5b3cc63ad7d6e002727ae4d52e819919fe16cc4591e8f4ffb804fa75af6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
